stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
     - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    - src/feature_engineering.py
    outs:
    - data/featured
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    - src/feature_engineering.py
    - src/model_building.py
    params:
    - model_building.max_iter
    outs:
    - model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    - src/feature_engineering.py
    - src/model_building.py
    - src/model_evaluation.py
    metrics:
    - metrics.json