stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw
      - src/data_preprocessing.py
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/raw
      - src/data_preprocessing.py
      - src/feature_engineering.py
    outs:
      - data/featured

  model_building:
    cmd: python src/model_building.py
    deps:
      - data/raw
      - src/data_preprocessing.py
      - src/feature_engineering.py
      - src/model_building.py
    params:
      - model_building.max_iter
    outs:
      - model/logistic_regression_model.pkl
      - model/decision_tree_model.pkl
      - model/xgboost_model.pkl
      - model/svm_model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - data/featured/test_featured.csv
      - model/logistic_regression_model.pkl
      - model/decision_tree_model.pkl
      - model/xgboost_model.pkl
      - model/svm_model.pkl
    outs:
      - outputs/metrics_logistic.json
      - outputs/metrics_decision_tree.json
      - outputs/metrics_xgboost.json
      - outputs/metrics_svm.json
   
  best_model:
    cmd: python src/best_model.py
    deps:
      - src/best_model.py
      - outputs/metrics_logistic.json
      - outputs/metrics_decision_tree.json
      - outputs/metrics_xgboost.json
      - outputs/metrics_svm.json
    outs:
      - best_model.pkl
    
  model_registration:
    cmd: python src/register_model.py
    deps:
      - best_model.pkl
      - src/register_model.py
    outs:
      - registered_model_version.txt


