data_ingestion:
  test_size: 0.3
  

model_building:
  max_iter: 150               # For Logistic Regression
  decision_tree_max_depth: 5  # For Decision Tree
  learning_rate: 0.12         # For XGBoost
  max_depth: 5               # For XGBoost
  n_estimators: 130          # For XGBoost
  svm_c: 1.0                   # For SVM


