artifact_location: file:///C:/Users/Subha/OneDrive/Desktop/Emp Attrition Rate Project/dagshub.com/datascience-1100/End-to-End-Employee-Attrition-Rate-Project.mlflow/0
creation_time: 1724893088094
experiment_id: '0'
last_update_time: 1724893088094
lifecycle_stage: active
name: Default
