name: CI Pipeline

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9]  # You can adjust the Python versions as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run linting
      run: |
        pip install flake8
        flake8 .
    
    - name: Run tests
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q
    
    - name: Deploy (optional)
      if: github.ref == 'refs/heads/master'  # Optional step to deploy only on push to master branch
      run: |
        echo "Deploying application..."
        # Add your deployment commands here

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/
