name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.16

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc
        pip install mlflow

    - name: Check environment variables
      run: |
        echo "DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }}"

    - name: Run DVC pipeline
      env:
        DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      run: |
        set -x  # Print each command before executing it
        dvc repro
