name: CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.16'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: best_model
        path: best_model.pkl
       
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc
        pip install mlflow
        pip install --upgrade xgboost
        pip install seaborn

    - name: Set up DagsHub credentials
      env:
       DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      run: |
       echo "DAGSHUB_PAT=${DAGSHUB_PAT}"

   
